export const availableModels = [
  { key: "groq", label: "Groq" },
  { key: "openai", label: "OpenAI" },
  { key: "gemini", label: "Gemini" },
  { key: "cohere", label: "Cohere" },
];

export const modelKeys = availableModels.map((model) => model.key);

export const proOptions = { account: "paid-pro", hideAttribution: true };

export const bannedWords: string[] = [
  "misleadin",
  "deceptive",
  "fraudulent",
  "stalking",
  "intimidation",
  "bullying",
  "harassment",
  "discrimination",
  "bribery",
  "corruption",
  "unethical",
  "explicit",
  "obscene",
  "inappropriate",
  "offensive",
  "threat",
  "cheat",
  "fraud",
  "scam",
  "spam",
  "malware",
  "virus",
  "pornography",
  "porn",
  "illegal",
  "drug",
  "firearm",
  "gun",
  "weapon",
  "violence",
  "killing",
  "murder",
  "hatecrime",
  "hate",
  "assassination",
  "assassin",
  "terrorism",
  "terrorist",
  "explosive",
  "bombing",
  "bomb",
];
